[project]
name = "public-doc-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "최덕진", email = "djchoi@in4ucloud.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
public-doc-bench = "public_doc_bench:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
